builds:
  - binary: ormesh
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
brew:
  github:
    owner: cmars
    name: homebrew-ormesh
dockers:
  - image: cmars/ormesh
